layout_spectrum: 1
color:
  saturation: 0.4108485
  brandStrength: 0.4085591
  lightness: 0
  rhythmicContrast: 0.8125672
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.764232
name: Beer
